export const SET_AUTHENTICATED_USER = "SET_AUTHENTICATED_USER";
export const USER_SIGNED_OUT = "USER_SIGNED_OUT";
export const SYNC_USER_INFORMATION = "SYNC_USER_INFORMATION";
export const FORCE_RELOGIN = "FORCE_RELOGIN";
export const FIREBASE_LOG_OUT = "FIREBASE_LOG_OUT";
