export const SYNC_SHOP = 'SYNC_SHOP';
export const SYNC_ALL_SHOP = 'SYNC_ALL_SHOP';
export const DELETE_SHOP = 'DELETE_SHOP';
export const ADD_SHOP = 'ADD_SHOP';
export const UPDATE_SHOP = 'UPDATE_SHOP';
export const ADD_SHOP_EMPLOYEE = 'ADD_SHOP_EMPLOYEE';
export const REMOVE_SHOP_EMPLOYEE = 'REMOVE_SHOP_EMPLOYEE';
export const UPDATE_NEW_SHOP_FIELD = 'UPDATE_NEW_SHOP_FIELD';
export const CLEAR_NEW_SHOP_FIELD = 'CLEAR_NEW_SHOP_FIELD';
export const SET_CURRENT_SHOP = 'SET_CURRENT_SHOP';

export const GET_ALL_SHOPS = 'GET_ALL_SHOPS';
