export const SYNC_EMPLOYEE = 'SYNC_EMPLOYEE';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const SYNC_EMPLOYEES = 'SYNC_EMPLOYEES';
export const SYNC_EMPLOYEES_BY_SHOP = 'SYNC_EMPLOYEES_BY_SHOP';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
