export const SYNC_FIREBASE_CARTS_DONE = 'SYNC_FIREBASE_CARTS_DONE';
export const SYNC_PROVINCES = 'SYNC_PROVINCES';
export const SYNC_DISTRICTS = 'SYNC_DISTRICTS';
export const SYNC_COMMUNES = 'SYNC_COMMUNES';
