export const SYNC_REPORT_DATA = 'SYNC_REPORT_DATA';
export const SYNC_ATTENDANCE_DATA = 'SYNC_ATTENDANCE_DATA';
export const LOADING_DATA = 'LOADING_DATA';
export const FINISHED_LOADING_DATA = 'FINISHED_LOADING_DATA';
export const SYNC_APP_ORDER_DATA = 'SYNC_APP_ORDER_DATA';
export const SYNC_APP_AND_NOT_APP_ORDER_DATA =
  'SYNC_APP_AND_NOT_APP_ORDER_DATA';
export const SYNC_BEST_SELLER_DATA = 'SYNC_BEST_SELLER_DATA';
export const SYNC_APP_GRAND_TOTAL_DATA = 'SYNC_APP_GRAND_TOTAL_DATA';
export const SYNC_APP_AND_NOT_APP_GRAND_TOTAL_DATA =
  'SYNC_APP_AND_NOT_APP_GRAND_TOTAL_DATA';
export const RESET_REPORT_DATA = 'RESET_REPORT_DATA';
export const SYNC_TOTAL_ORDER = 'SYNC_TOTAL_ORDER';
export const SYNC_TOTAL_GRAND_TOTAL = 'SYNC_TOTAL_GRAND_TOTAL';
export const SYNC_ORDER_KPI = 'SYNC_ORDER_KPI';
export const SYNC_EMPLOYEE_ORDER = 'SYNC_EMPLOYEE_ORDER';

export const SYNC_ORDER_KPI_BY_STORE = 'SYNC_ORDER_KPI_BY_STORE';
